### ISSUE TITLE
Icon font changing `content` when loaded

### ISSUE THREAD

**Issue by zachleat** [KenjiBaheux/css-font-rendering#19]
One of the fringe cases that this property does not solve is that it does not solve the use case of changing the `content` property in CSS from a fallback unicode glyph to a new `content` glyph after the icon font has loading. It requires you to map your icons directly to the code point of the fallback character, which isn’t always easy since most icon fonts are supplied as part of a icon font package.

For example, while the font is loading, show `\2261` hamburger menu (ok, the triple bar math symbol, but whatever). Then, when the font has loaded, show the actual font-icon supplied hamburger menu (probably assigned to something other than `\2261`, likely a decision not made by you).

I wrote an article about these icon font use cases awhile back:
http://www.filamentgroup.com/lab/bulletproof_icon_fonts.html

I consider this to be a edge case for sure and I hesitate to even post it in here for a couple of reasons:

* Icon fonts, I believe, are going away. They’re difficult to use properly and I’ve found SVG much easier to use.
* Fallback glyphs may not be consistent across operating systems and devices (http://unicode.johnholtripley.co.uk/)
* Modifying the code points in the font is an acceptable workaround, in my opinion. Many authors may disagree with this, I don’t know.

So, here is the ticket for posterity (feel free to close). I don’t want this edge case to hold anything up because this property is sorely needed.

**Comment by jakearchibald** [comment]
Yeah, I'd say the font loading API can be used to cater for this http://dev.w3.org/csswg/css-font-loading/

**Comment by KenjiBaheux** [comment]
+1 to Jake.
Let me close this issue.
